### ISSUE TITLE
refresh dashboard page

### ISSUE THREAD

**Issue by vdasus** [mmacneil/VueASPNETCore2WebApiAuth#1]
when you refreshing page which require authorization - returned 401 (unauthorized)...

i mean:
register user
go to the dashboard/home
all is ok
press refresh (F5)
crash boom bang

I think, that problem here because interceptor not "intercepts" when page refreshed:
```
axios.interceptors.request.use((config) => {
    const authToken = store.getters['auth/authToken'];
    if (authToken) {
        config.headers.Authorization = `Bearer ${authToken}`;
    }
    return config;
}, (err) => {
    return Promise.reject(err);
});
```

![20180425125529cf1ij](https://user-images.githubusercontent.com/4681649/39238868-03098ce8-4888-11e8-8ad7-ea306a969728.png)

**Comment by hosney** [comment]
Did you find a solution for this?

**Comment by sebasijan** [comment]
I had this same issue and just moved the interceptor to its own file

```
import axios from 'axios';
import store from '../store/store';

axios.interceptors.request.use((config: any) => {
    console.log('interception');

    const authToken = store.getters['auth/authToken'];
    if (authToken) {
      config.headers.Authorization = `Bearer ${authToken}`;
    }
    return config;
  }, (err: any) => {
    return Promise.reject(err);
  });

```

and import it in `main.ts`

    import './axios/authInterceptors';
