### ISSUE TITLE
You may need an appropriate loader to handle this file type - getters

### ISSUE THREAD

**Issue by maciz84** [mmacneil/VueASPNETCore2WebApiAuth#2]
Hi Guys,

I am getting this error when compiling:

`ERROR in ./Store/modules/auth.ts
Module parse failed: Store\modules\auth.ts Unexpected token (8:31)
You may need an appropriate loader to handle this file type.
| 
| const getters = {
|     isAuthenticated: (authState: any) => !!authState.token,
|     authStatus: (authState: any) => authState.status,
|     authToken: (authState: any) => authState.token,
 @ ./Store/store.ts 3:0-34
 @ ./ClientApp/boot.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.ts
`

Does anyone know how I can fix this?

**Comment by neogn95** [comment]
Unable to simulate this issue. Have you tried with the latest update? @maciz84
